const colors = [
  "Black",
  "grey11",
  "grey21",
  "DimGray",
  "DarkGray",
  "Silver",
  "LightGrey",
  "DarkBlue",
  "Blue",
  "RoyalBlue",
  "SkyBlue",
  "DarkTurquoise",
  "Turquoise",
  "Teal",
  "Aquamarine",
  "MediumSpringGreen",
  "LightGreen",
  "SeaGreen",
  "Green",
  "ForestGreen",
  "LimeGreen",
  "Lime",
  "LawnGreen",
  "Chartreuse",
  "GreenYellow",
  "YellowGreen",
  "OliveDrab",
  "DarkOliveGreen",
  "Olive",
  "DarkKhaki",
  "Goldenrod",
  "DarkGoldenrod",
  "SaddleBrown",
  "Sienna",
  "RosyBrown",
  "Peru",
  "Chocolate",
  "SandyBrown",
  "NavajoWhite",
  "Wheat",
  "BurlyWood",
  "Tan",
  "MediumSlateBlue",
  "MediumPurple",
  "BlueViolet",
  "Indigo",
  "DarkViolet",
  "DarkOrchid",
  "MediumOrchid",
  "Purple",
  "DarkMagenta",
  "Violet",
  "Orchid",
  "Plum",
  "MediumVioletRed",
  "DeepPink",
  "HotPink",
  "PaleVioletRed",
  "LightPink",
  "Pink",
  "LightCoral",
  "IndianRed",
  "Crimson",
  "Maroon",
  "DarkRed",
  "FireBrick",
  "Brown",
  "Salmon",
  "DarkSalmon",
  "LightSalmon",
  "Coral",
  "Tomato",
  "Red",
  "OrangeRed",
  "DarkOrange",
  "Orange",
  "Yellow",
  "Linen",
  "AntiqueWhite",
  "BlanchedAlmond",
  "Bisque",
  "LightYellow",
  "PapayaWhip",
  "Moccasin",
  "PaleGoldenrod",
  "MistyRose",
  "LavenderBlush",
  "Lavender",
  "Thistle",
  "Azure",
  "LightCyan",
  "PowderBlue",
  "PaleTurquoise",
  "Honeydew",
  "MintCream",
];
const btn = document.querySelector("#btn");
const color = document.querySelector(".color");

btn.addEventListener("click", () => {
  //get random number betwenn 0 - 4
  let randomNumber = getRandomNumber();
  document.body.style.backgroundColor = colors[randomNumber];
  color.textContent = colors[randomNumber];
});

function getRandomNumber() {
  return Math.floor(Math.random() * colors.length);
}
